import type { FastifyPluginAsync, FastifyReply } from "fastify";
import { projectCoreState, type ActorSet, type ProjectRole } from "../project-core-state.js";
import { screensPriorityState, type PriorityScheme } from "../screens-priority-state.js";
import { getSchemesState, type PermissionScheme } from "../schemes-state.js";
import { jiraError } from "../shared/errors.js";
import { serializeNamedResource, serializeProject, serializeStatus, serializeUser } from "../shared/serialization.js";
import { workflowSchemesState, type StoredWorkflowScheme } from "../shared/workflow-schemes-state.js";
import type { JiraProject } from "../types.js";

type Query = Record<string, string | string[] | boolean | undefined>;

function fail(reply: FastifyReply, status: number, message: string, field?: string) {
  return reply.code(status).send(field ? jiraError([], { [field]: message }) : jiraError([message]));
}
function object(value: unknown): Record<string, unknown> | undefined { return value !== null && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : undefined; }
function integer(value: string | string[] | boolean | undefined, fallback: number): number | undefined { if (value === undefined) return fallback; const text = String(Array.isArray(value) ? value[0] : value); return /^\d+$/.test(text) ? Number(text) : undefined; }
function list(value: string | string[] | boolean | undefined): string[] { if (value === undefined || typeof value === "boolean") return []; return (Array.isArray(value) ? value : [value]).flatMap((item) => item.split(",")).map((item) => item.trim()).filter(Boolean); }

const projectTypes = [
  { key: "software", formattedKey: "Software", color: "#2684ff", descriptionI18nKey: "jira.project.type.software" },
  { key: "business", formattedKey: "Business", color: "#6554c0", descriptionI18nKey: "jira.project.type.business" },
  { key: "service_desk", formattedKey: "Service Desk", color: "#00b8d9", descriptionI18nKey: "jira.project.type.service_desk" },
] as const;

function findProject(app: Parameters<FastifyPluginAsync>[0], value: string) { return app.jira.store.state.projects.find((project) => project.id === value || project.key.toLowerCase() === value.toLowerCase()); }
function roleActors(state: ReturnType<typeof projectCoreState>, projectId: string, roleId: number): ActorSet { return state.projectRoleActors[projectId]?.[String(roleId)] ?? state.defaultRoleActors[String(roleId)] ?? { users: [], groups: [] }; }
function actorJson(app: Parameters<FastifyPluginAsync>[0], actors: ActorSet) { return [...actors.users.map((name) => ({ name, avatarUrl: `${app.jira.baseUrl}/secure/useravatar?ownerId=${encodeURIComponent(name)}` })), ...actors.groups.map((name) => ({ name, avatarUrl: `${app.jira.baseUrl}/secure/groupavatar?group=${encodeURIComponent(name)}` }))]; }
function roleJson(app: Parameters<FastifyPluginAsync>[0], role: ProjectRole, actors?: ActorSet, project?: JiraProject) { return { id: role.id, name: role.name, description: role.description, self: project ? `${app.jira.baseUrl}/rest/api/2/project/${project.key}/role/${role.id}` : `${app.jira.baseUrl}/rest/api/2/role/${role.id}`, actors: actorJson(app, actors ?? { users: [], groups: [] }) }; }
function avatarJson(value: { id: string; owner: string; selected: boolean }) { return { id: value.id, owner: value.owner, selected: value.selected }; }
function permissionSchemeJson(app: Parameters<FastifyPluginAsync>[0], scheme: PermissionScheme) { return { id: scheme.id, name: scheme.name, description: scheme.description, expand: "permissions", self: `${app.jira.baseUrl}/rest/api/2/permissionscheme/${scheme.id}`, permissions: scheme.permissions.map((grant) => ({ ...grant, self: `${app.jira.baseUrl}/rest/api/2/permissionscheme/${scheme.id}/permission/${grant.id}` })) }; }
function prioritySchemeJson(app: Parameters<FastifyPluginAsync>[0], scheme: PriorityScheme) { return { ...structuredClone(scheme), self: `${app.jira.baseUrl}/rest/api/2/priorityscheme/${scheme.id}` }; }
function workflowSchemeJson(app: Parameters<FastifyPluginAsync>[0], scheme: StoredWorkflowScheme) { return { id: scheme.id, name: scheme.name, description: scheme.description, draft: scheme.draft, defaultWorkflow: scheme.defaultWorkflow, issueTypeMappings: scheme.issueTypeMappings, issueTypes: Object.fromEntries(app.jira.store.state.issueTypes.filter((type) => type.id in scheme.issueTypeMappings).map((type) => [type.id, serializeNamedResource(type, app.jira.baseUrl, "issuetype")])), self: `${app.jira.baseUrl}/rest/api/2/workflowscheme/${scheme.id}`, lastModified: "06/Aug/26 12:00 PM", lastModifiedUser: serializeUser(app.jira.currentUser(), app.jira.baseUrl) }; }

const routes: FastifyPluginAsync = async (app) => {
  app.addContentTypeParser(/^multipart\/form-data(?:;.*)?$/, { parseAs: "buffer" }, (_request, body, done) => done(null, body));

  app.get("/rest/api/2/permissions", async () => ({ permissions: permissionCatalog(false) }));
  app.get("/rest/api/2/mypermissions", async (request, reply) => {
    const query = request.query as Query;
    const projectRef = typeof query.projectKey === "string" ? query.projectKey : typeof query.projectId === "string" ? query.projectId : undefined;
    if (projectRef && !findProject(app, projectRef)) return fail(reply, 404, "The project does not exist.");
    if (typeof query.issueKey === "string" && !app.jira.store.state.issues.some((issue) => issue.key === query.issueKey)) return fail(reply, 404, "The issue does not exist.");
    if (typeof query.issueId === "string" && !app.jira.store.state.issues.some((issue) => issue.id === query.issueId)) return fail(reply, 404, "The issue does not exist.");
    return { permissions: permissionCatalog(true) };
  });

  app.post("/rest/api/2/project", async (request, reply) => {
    const body = object(request.body);
    const key = typeof body?.key === "string" ? body.key.trim().toUpperCase() : "";
    const name = typeof body?.name === "string" ? body.name.trim() : "";
    const type = typeof body?.projectTypeKey === "string" ? body.projectTypeKey : "software";
    const leadName = typeof body?.lead === "string" ? body.lead : "developer";
    if (!/^[A-Z][A-Z0-9]{1,9}$/.test(key) || !name) return fail(reply, 400, "A valid project key and name are required.");
    if (!projectTypes.some((value) => value.key === type)) return fail(reply, 400, "The project type does not exist.", "projectTypeKey");
    if (app.jira.store.state.projects.some((value) => value.key === key || value.name.toLowerCase() === name.toLowerCase())) return fail(reply, 409, "A project with this key or name already exists.");
    const lead = app.jira.store.state.users.find((user) => user.name === leadName || user.key === leadName);
    if (!lead) return fail(reply, 400, "The project lead does not exist.", "lead");
    if (body?.assigneeType !== undefined && body.assigneeType !== "PROJECT_LEAD" && body.assigneeType !== "UNASSIGNED") return fail(reply, 400, "assigneeType must be PROJECT_LEAD or UNASSIGNED.", "assigneeType");
    const schemeState = getSchemesState(app.jira.store);
    const permissionSchemeId = Number(body?.permissionScheme ?? 10000), notificationSchemeId = Number(body?.notificationScheme ?? 10000), issueSecuritySchemeId = Number(body?.issueSecurityScheme ?? 10000);
    if (!schemeState.permissionSchemes.some((value) => value.id === permissionSchemeId)) return fail(reply, 400, "The permission scheme does not exist.", "permissionScheme");
    if (!schemeState.notificationSchemes.some((value) => value.id === notificationSchemeId)) return fail(reply, 400, "The notification scheme does not exist.", "notificationScheme");
    if (!schemeState.issueSecuritySchemes.some((value) => value.id === issueSecuritySchemeId)) return fail(reply, 400, "The issue security scheme does not exist.", "issueSecurityScheme");
    const workflowState = workflowSchemesState(app.jira.store); const workflowSchemeId = Number(body?.workflowSchemeId ?? 10000); const workflowScheme = workflowState.schemes.find((value) => value.id === workflowSchemeId);
    if (!workflowScheme) return fail(reply, 400, "The workflow scheme does not exist.", "workflowSchemeId");
    const state = projectCoreState(app.jira.store);
    const id = String(state.projectCounter++);
    const project: JiraProject = { id, key, name, projectTypeKey: type as JiraProject["projectTypeKey"], simplified: false, archived: false, lead, avatarUrls: { "16x16": "/secure/projectavatar?size=xsmall", "24x24": "/secure/projectavatar?size=small", "32x32": "/secure/projectavatar?size=medium", "48x48": "/secure/projectavatar?size=large" } };
    app.jira.store.state.projects.push(project);
    state.projects[id] = { description: typeof body?.description === "string" ? body.description : "", url: typeof body?.url === "string" ? body.url : "", assigneeType: body?.assigneeType === "UNASSIGNED" ? "UNASSIGNED" : "PROJECT_LEAD", avatarId: "10000", properties: {}, avatars: [{ id: "10000", owner: "system", selected: true, system: true }], components: [], versions: [], permissionSchemeId, notificationSchemeId, issueSecuritySchemeId, prioritySchemeId: 0 };
    workflowScheme.projectIds.push(id); screensPriorityState(app.jira.store).prioritySchemes.find((value) => value.defaultScheme)?.projectKeys.push(key); (schemeState.issueTypeProjectAssociations["10000"] ??= []).push(id);
    app.jira.store.save();
    return reply.code(201).send({ id: Number(id), key, self: `${app.jira.baseUrl}/rest/api/2/project/${id}` });
  });

  app.get("/rest/api/2/project/type", async () => projectTypes);
  app.get("/rest/api/2/project/type/:projectTypeKey/accessible", async (request, reply) => projectType(request, reply));
  app.get("/rest/api/2/project/type/:projectTypeKey", async (request, reply) => projectType(request, reply));

  app.put("/rest/api/2/project/:projectIdOrKey", async (request, reply) => {
    const { projectIdOrKey } = request.params as { projectIdOrKey: string }; const project = findProject(app, projectIdOrKey); if (!project) return fail(reply, 404, "The project does not exist.");
    const body = object(request.body); if (!body) return fail(reply, 400, "The project update must be a JSON object.");
    const key = body.key === undefined ? project.key : typeof body.key === "string" ? body.key.trim().toUpperCase() : "";
    const name = body.name === undefined ? project.name : typeof body.name === "string" ? body.name.trim() : "";
    if (!/^[A-Z][A-Z0-9]{1,9}$/.test(key) || !name) return fail(reply, 400, "The project key or name is invalid.");
    if (app.jira.store.state.projects.some((value) => value.id !== project.id && (value.key === key || value.name.toLowerCase() === name.toLowerCase()))) return fail(reply, 400, "The project key or name is already used.");
    if (body.lead !== undefined) { const lead = typeof body.lead === "string" ? app.jira.store.state.users.find((user) => user.name === body.lead || user.key === body.lead) : undefined; if (!lead) return fail(reply, 400, "The project lead does not exist.", "lead"); project.lead = lead; }
    const state = projectCoreState(app.jira.store); const details = state.projects[project.id]; const oldKey = project.key; project.key = key; project.name = name;
    if (body.projectTypeKey !== undefined) { if (typeof body.projectTypeKey !== "string" || !projectTypes.some((value) => value.key === body.projectTypeKey)) return fail(reply, 400, "The project type does not exist.", "projectTypeKey"); project.projectTypeKey = body.projectTypeKey as JiraProject["projectTypeKey"]; }
    if (body.assigneeType !== undefined && body.assigneeType !== "PROJECT_LEAD" && body.assigneeType !== "UNASSIGNED") return fail(reply, 400, "assigneeType must be PROJECT_LEAD or UNASSIGNED.", "assigneeType");
    const schemes = getSchemesState(app.jira.store);
    if (body.permissionScheme !== undefined) { const id = Number(body.permissionScheme); if (!schemes.permissionSchemes.some((value) => value.id === id)) return fail(reply, 400, "The permission scheme does not exist.", "permissionScheme"); details.permissionSchemeId = id; }
    if (body.notificationScheme !== undefined) { const id = Number(body.notificationScheme); if (!schemes.notificationSchemes.some((value) => value.id === id)) return fail(reply, 400, "The notification scheme does not exist.", "notificationScheme"); details.notificationSchemeId = id; }
    if (body.issueSecurityScheme !== undefined) { const id = Number(body.issueSecurityScheme); if (!schemes.issueSecuritySchemes.some((value) => value.id === id)) return fail(reply, 400, "The issue security scheme does not exist.", "issueSecurityScheme"); details.issueSecuritySchemeId = id; }
    if (oldKey !== key) for (const scheme of screensPriorityState(app.jira.store).prioritySchemes) scheme.projectKeys = scheme.projectKeys.map((value) => value === oldKey ? key : value);
    if (typeof body.description === "string") details.description = body.description; if (typeof body.url === "string") details.url = body.url; if (body.assigneeType === "PROJECT_LEAD" || body.assigneeType === "UNASSIGNED") details.assigneeType = body.assigneeType;
    app.jira.store.save(); return serializeProject(project, app.jira.baseUrl);
  });

  app.delete("/rest/api/2/project/:projectIdOrKey", async (request, reply) => { const { projectIdOrKey } = request.params as { projectIdOrKey: string }; const project = findProject(app, projectIdOrKey); if (!project) return fail(reply, 404, "The project does not exist."); app.jira.store.state.projects = app.jira.store.state.projects.filter((value) => value.id !== project.id); app.jira.store.state.issues = app.jira.store.state.issues.filter((issue) => issue.fields.project.id !== project.id); const state = projectCoreState(app.jira.store); delete state.projects[project.id]; delete state.projectRoleActors[project.id]; const schemes = getSchemesState(app.jira.store); for (const ids of Object.values(schemes.issueTypeProjectAssociations)) { const index = ids.indexOf(project.id); if (index >= 0) ids.splice(index, 1); } for (const scheme of workflowSchemesState(app.jira.store).schemes) scheme.projectIds = scheme.projectIds.filter((id) => id !== project.id); for (const scheme of screensPriorityState(app.jira.store).prioritySchemes) scheme.projectKeys = scheme.projectKeys.filter((key) => key !== project.key); app.jira.store.save(); return reply.code(204).send(); });
  app.put("/rest/api/2/project/:projectIdOrKey/archive", async (request, reply) => archive(request, reply, true, 204));
  app.put("/rest/api/2/project/:projectIdOrKey/restore", async (request, reply) => archive(request, reply, false, 202));

  app.get("/rest/api/2/project/:projectIdOrKey/avatars", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); return projectCoreState(app.jira.store).projects[project.id].avatars.map(avatarJson); });
  app.post("/rest/api/2/project/:projectIdOrKey/avatar/temporary", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); const body = request.body; const text = Buffer.isBuffer(body) ? body.toString("utf8") : ""; if (!Buffer.isBuffer(body) || !/name="file"/i.test(text)) return fail(reply, 400, "A multipart avatar file is required."); const details = projectCoreState(app.jira.store).projects[project.id]; details.temporaryAvatar = { size: body.length }; app.jira.store.save(); const cropping = { cropperOffsetX: 0, cropperOffsetY: 0, cropperWidth: 128, needsCropping: true, url: `${app.jira.baseUrl}/secure/temporaryavatar?projectId=${project.id}` }; return reply.code(201).type("text/html").send(JSON.stringify(cropping)); });
  app.post("/rest/api/2/project/:projectIdOrKey/avatar", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); const body = object(request.body); if (!body || !Number.isInteger(body.cropperWidth) || Number(body.cropperWidth) <= 0) return fail(reply, 400, "Cropping instructions are invalid."); const state = projectCoreState(app.jira.store); const details = state.projects[project.id]; if (!details.temporaryAvatar) return fail(reply, 400, "No temporary avatar is available."); details.avatars.forEach((value) => value.selected = false); const avatar = { id: String(state.avatarCounter++), owner: "developer", selected: true, system: false }; details.avatars.push(avatar); details.avatarId = avatar.id; delete details.temporaryAvatar; app.jira.store.save(); return reply.code(201).send(avatarJson(avatar)); });
  app.put("/rest/api/2/project/:projectIdOrKey/avatar", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); const body = object(request.body); const id = typeof body?.id === "string" ? body.id : String(body?.id ?? ""); const details = projectCoreState(app.jira.store).projects[project.id]; const avatar = details.avatars.find((value) => value.id === id); if (!avatar) return fail(reply, 400, "The avatar does not exist."); details.avatars.forEach((value) => value.selected = value.id === id); details.avatarId = id; app.jira.store.save(); return reply.code(204).send(); });
  app.delete("/rest/api/2/project/:projectIdOrKey/avatar/:id", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); const { id } = request.params as { id: string }; const details = projectCoreState(app.jira.store).projects[project.id]; const index = details.avatars.findIndex((value) => value.id === id); if (index < 0 || details.avatars[index].system || details.avatars[index].selected) return fail(reply, 404, "The avatar cannot be deleted."); details.avatars.splice(index, 1); app.jira.store.save(); return reply.code(204).send(); });

  app.get("/rest/api/2/project/:projectIdOrKey/components", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); return projectCoreState(app.jira.store).projects[project.id].components.map((component) => ({ ...component, project: project.key, assigneeType: "PROJECT_LEAD", archived: false, deleted: false, lead: serializeUser(project.lead, app.jira.baseUrl), leadUserName: project.lead.name, self: `${app.jira.baseUrl}/rest/api/2/component/${component.id}` })); });
  app.get("/rest/api/2/project/:projectIdOrKey/properties", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); const props = projectCoreState(app.jira.store).projects[project.id].properties; return { keys: Object.keys(props).sort().map((key) => ({ key, self: `${app.jira.baseUrl}/rest/api/2/project/${project.id}/properties/${encodeURIComponent(key)}` })) }; });
  app.get("/rest/api/2/project/:projectIdOrKey/properties/:propertyKey", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); const { propertyKey } = request.params as { propertyKey: string }; const props = projectCoreState(app.jira.store).projects[project.id].properties; if (!(propertyKey in props)) return fail(reply, 404, "The project property does not exist."); return { key: propertyKey, value: typeof props[propertyKey] === "string" ? props[propertyKey] : JSON.stringify(props[propertyKey]) }; });
  app.put("/rest/api/2/project/:projectIdOrKey/properties/:propertyKey", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); const { propertyKey } = request.params as { propertyKey: string }; const body = object(request.body); if (!body || !("value" in body) || body.value === "" || Buffer.byteLength(propertyKey) > 255) return fail(reply, 400, "A non-empty property value and valid key are required."); const props = projectCoreState(app.jira.store).projects[project.id].properties; const existed = propertyKey in props; props[propertyKey] = body.value; app.jira.store.save(); return reply.code(existed ? 200 : 201).send(); });
  app.delete("/rest/api/2/project/:projectIdOrKey/properties/:propertyKey", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); const { propertyKey } = request.params as { propertyKey: string }; const props = projectCoreState(app.jira.store).projects[project.id].properties; if (!(propertyKey in props)) return fail(reply, 404, "The project property does not exist."); delete props[propertyKey]; app.jira.store.save(); return reply.code(204).send(); });

  app.get("/rest/api/2/project/:projectIdOrKey/role", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); return Object.fromEntries(projectCoreState(app.jira.store).roles.map((role) => [role.name, `${app.jira.baseUrl}/rest/api/2/project/${project.key}/role/${role.id}`])); });
  app.get("/rest/api/2/project/:projectIdOrKey/role/:id", async (request, reply) => projectRole(request, reply));
  app.put("/rest/api/2/project/:projectIdOrKey/role/:id", async (request, reply) => mutateProjectRole(request, reply, true));
  app.post("/rest/api/2/project/:projectIdOrKey/role/:id", async (request, reply) => mutateProjectRole(request, reply, false));
  app.delete("/rest/api/2/project/:projectIdOrKey/role/:id", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); const { id } = request.params as { id: string }; const state = projectCoreState(app.jira.store); const role = state.roles.find((value) => String(value.id) === id); if (!role) return fail(reply, 404, "The project role does not exist."); const query = request.query as Query; const actors = { ...roleActors(state, project.id, role.id), users: [...roleActors(state, project.id, role.id).users], groups: [...roleActors(state, project.id, role.id).groups] }; const users = list(query.user), groups = list(query.group); if (!users.length && !groups.length) return fail(reply, 400, "A user or group is required."); actors.users = actors.users.filter((value) => !users.includes(value)); actors.groups = actors.groups.filter((value) => !groups.includes(value)); (state.projectRoleActors[project.id] ??= {})[id] = actors; app.jira.store.save(); return reply.code(204).send(); });

  app.get("/rest/api/2/project/:projectIdOrKey/statuses", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); return app.jira.store.state.issueTypes.map((type) => ({ ...serializeNamedResource(type, app.jira.baseUrl, "issuetype"), statuses: app.jira.store.state.statuses.map((status) => serializeStatus(status, app.jira.baseUrl)) })); });
  app.put("/rest/api/2/project/:projectIdOrKey/type/:newProjectTypeKey", async (request, reply) => { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); const { newProjectTypeKey } = request.params as { newProjectTypeKey: string }; if (!projectTypes.some((value) => value.key === newProjectTypeKey)) return fail(reply, 400, "The project type does not exist."); project.projectTypeKey = newProjectTypeKey as JiraProject["projectTypeKey"]; app.jira.store.save(); return serializeProject(project, app.jira.baseUrl); });
  app.get("/rest/api/2/project/:projectIdOrKey/versions", async (request, reply) => versions(request, reply, false));
  app.get("/rest/api/2/project/:projectIdOrKey/version", async (request, reply) => versions(request, reply, true));

  app.get("/rest/api/2/project/:projectKeyOrId/issuesecuritylevelscheme", async (request, reply) => { const project = projectParam(request, "projectKeyOrId"); if (!project) return fail(reply, 404, "The project does not exist."); const details = projectCoreState(app.jira.store).projects[project.id]; const scheme = getSchemesState(app.jira.store).issueSecuritySchemes.find((value) => value.id === details.issueSecuritySchemeId); if (!scheme) return fail(reply, 404, "No issue security scheme is assigned."); return { ...scheme, self: `${app.jira.baseUrl}/rest/api/2/issuesecurityschemes/${scheme.id}`, levels: scheme.levels.map((level) => ({ ...level, self: `${app.jira.baseUrl}/rest/api/2/securitylevel/${level.id}` })) }; });
  app.get("/rest/api/2/project/:projectKeyOrId/notificationscheme", async (request, reply) => { const project = projectParam(request, "projectKeyOrId"); if (!project) return fail(reply, 404, "The project does not exist."); const details = projectCoreState(app.jira.store).projects[project.id]; const scheme = getSchemesState(app.jira.store).notificationSchemes.find((value) => value.id === details.notificationSchemeId); if (!scheme) return fail(reply, 404, "No notification scheme is assigned."); return { ...scheme, expand: "notificationSchemeEvents", self: `${app.jira.baseUrl}/rest/api/2/notificationscheme/${scheme.id}` }; });
  app.get("/rest/api/2/project/:projectKeyOrId/permissionscheme", async (request, reply) => permissionScheme(request, reply));
  app.put("/rest/api/2/project/:projectKeyOrId/permissionscheme", async (request, reply) => permissionScheme(request, reply, true));
  app.get("/rest/api/2/project/:projectKeyOrId/priorityscheme", async (request, reply) => priorityScheme(request, reply));
  app.put("/rest/api/2/project/:projectKeyOrId/priorityscheme", async (request, reply) => priorityScheme(request, reply, true));
  app.delete("/rest/api/2/project/:projectKeyOrId/priorityscheme/:schemeId", async (request, reply) => { const project = projectParam(request, "projectKeyOrId"); if (!project) return fail(reply, 404, "The project does not exist."); const { schemeId } = request.params as { schemeId: string }; const details = projectCoreState(app.jira.store).projects[project.id]; if (String(details.prioritySchemeId) !== schemeId) return fail(reply, 400, "The priority scheme is not assigned to this project."); const schemes = screensPriorityState(app.jira.store).prioritySchemes; schemes.forEach((scheme) => scheme.projectKeys = scheme.projectKeys.filter((key) => key !== project.key)); const target = schemes.find((scheme) => scheme.defaultScheme)!; target.projectKeys.push(project.key); details.prioritySchemeId = target.id; app.jira.store.save(); return prioritySchemeJson(app, target); });
  app.get("/rest/api/2/project/:projectKeyOrId/securitylevel", async (request, reply) => { const project = projectParam(request, "projectKeyOrId"); if (!project) return fail(reply, 404, "The project does not exist."); const details = projectCoreState(app.jira.store).projects[project.id]; const scheme = getSchemesState(app.jira.store).issueSecuritySchemes.find((value) => value.id === details.issueSecuritySchemeId); return { levels: (scheme?.levels ?? []).map((level) => ({ ...level, self: `${app.jira.baseUrl}/rest/api/2/securitylevel/${level.id}` })) }; });
  app.get("/rest/api/2/project/:projectKeyOrId/workflowscheme", async (request, reply) => { const project = projectParam(request, "projectKeyOrId"); if (!project) return fail(reply, 404, "The project does not exist."); const scheme = workflowSchemesState(app.jira.store).schemes.find((value) => value.projectIds.includes(project.id)); if (!scheme) return fail(reply, 404, "No workflow scheme is assigned."); return workflowSchemeJson(app, scheme); });

  app.get("/rest/api/2/projects/picker", async (request, reply) => { const query = request.query as Query; const text = typeof query.query === "string" ? query.query.trim().toLowerCase() : ""; const allowEmpty = String(query.allowEmptyQuery ?? "false") === "true"; if (!text && !allowEmpty) return { header: "No projects found", total: 0, projects: [] }; const max = integer(query.maxResults, 50); if (max === undefined) return fail(reply, 400, "maxResults must be non-negative."); const matches = app.jira.store.state.projects.filter((project) => !project.archived && `${project.key} ${project.name}`.toLowerCase().includes(text)); return { header: `Showing ${Math.min(max, matches.length)} of ${matches.length} matching projects`, total: matches.length, projects: matches.slice(0, max).map((project) => ({ id: project.id, key: project.key, name: project.name, avatar: `${app.jira.baseUrl}/secure/projectavatar?pid=${project.id}`, html: `${project.name} (${project.key})` })) }; });
  app.get("/rest/api/2/projectvalidate/key", async (request) => { const query = request.query as Query; const key = typeof query.key === "string" ? query.key.trim().toUpperCase() : ""; const errors: Record<string, string> = {}; if (!/^[A-Z][A-Z0-9]{1,9}$/.test(key)) errors.key = "Project keys must start with a letter and contain only uppercase letters and numbers."; else if (app.jira.store.state.projects.some((project) => project.key === key)) errors.key = "A project with that key already exists."; return { errorMessages: [], errors }; });

  app.get("/rest/api/2/role", async () => projectCoreState(app.jira.store).roles.map((role) => roleJson(app, role, projectCoreState(app.jira.store).defaultRoleActors[String(role.id)])));
  app.post("/rest/api/2/role", async (request, reply) => roleMutation(request, reply, "create"));
  app.get("/rest/api/2/role/:id/actors", async (request, reply) => globalActors(request, reply));
  app.post("/rest/api/2/role/:id/actors", async (request, reply) => globalActors(request, reply, "add"));
  app.delete("/rest/api/2/role/:id/actors", async (request, reply) => globalActors(request, reply, "delete"));
  app.get("/rest/api/2/role/:id", async (request, reply) => { const { id } = request.params as { id: string }; const state = projectCoreState(app.jira.store); const role = state.roles.find((value) => String(value.id) === id); if (!role) return fail(reply, 404, "The project role does not exist."); return roleJson(app, role, state.defaultRoleActors[id]); });
  app.put("/rest/api/2/role/:id", async (request, reply) => roleMutation(request, reply, "full"));
  app.post("/rest/api/2/role/:id", async (request, reply) => roleMutation(request, reply, "partial"));
  app.delete("/rest/api/2/role/:id", async (request, reply) => { const { id } = request.params as { id: string }; const state = projectCoreState(app.jira.store); const index = state.roles.findIndex((value) => String(value.id) === id); if (index < 0) return fail(reply, 404, "The project role does not exist."); const query = request.query as Query; const swap = typeof query.swap === "string" ? state.roles.find((value) => String(value.id) === query.swap) : undefined; const inUse = Object.values(state.projectRoleActors).some((roles) => id in roles); if (inUse && !swap) return fail(reply, 409, "A replacement role is required while the role is in use."); if (swap) for (const roles of Object.values(state.projectRoleActors)) if (roles[id]) { roles[String(swap.id)] = roles[id]; delete roles[id]; } state.roles.splice(index, 1); delete state.defaultRoleActors[id]; app.jira.store.save(); return reply.code(204).send(); });

  function projectParam(request: { params: unknown }, key = "projectIdOrKey") { return findProject(app, String((request.params as Record<string, string>)[key])); }
  function projectType(request: { params: unknown }, reply: FastifyReply) { const { projectTypeKey } = request.params as { projectTypeKey: string }; const result = projectTypes.find((value) => value.key === projectTypeKey); return result ?? fail(reply, 404, "The project type does not exist."); }
  function archive(request: { params: unknown }, reply: FastifyReply, archived: boolean, status: number) { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); project.archived = archived; app.jira.store.save(); return reply.code(status).send(); }
  function projectRole(request: { params: unknown }, reply: FastifyReply) { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); const { id } = request.params as { id: string }; const state = projectCoreState(app.jira.store); const role = state.roles.find((value) => String(value.id) === id); if (!role) return fail(reply, 404, "The project role does not exist."); return roleJson(app, role, roleActors(state, project.id, role.id), project); }
  function actorSet(body: Record<string, unknown>, categorised: boolean): ActorSet | undefined { const source = categorised ? object(body.categorisedActors) : body; if (!source) return undefined; const users = source["atlassian-user-role-actor"] ?? source.user ?? []; const groups = source["atlassian-group-role-actor"] ?? source.group ?? []; if (!Array.isArray(users) || !users.every((value) => typeof value === "string") || !Array.isArray(groups) || !groups.every((value) => typeof value === "string")) return undefined; if (users.some((name) => !app.jira.store.state.users.some((user) => user.name === name || user.key === name))) return undefined; return { users: [...new Set(users as string[])], groups: [...new Set(groups as string[])] }; }
  function mutateProjectRole(request: { params: unknown; body: unknown }, reply: FastifyReply, replace: boolean) { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); const { id } = request.params as { id: string }; const state = projectCoreState(app.jira.store); const role = state.roles.find((value) => String(value.id) === id); if (!role) return fail(reply, 404, "The project role does not exist."); const body = object(request.body); const incoming = body ? actorSet(body, replace) : undefined; if (!incoming) return fail(reply, 400, "Valid user and group actor arrays are required."); const current = roleActors(state, project.id, role.id); const actors = replace ? incoming : { users: [...new Set([...current.users, ...incoming.users])], groups: [...new Set([...current.groups, ...incoming.groups])] }; (state.projectRoleActors[project.id] ??= {})[id] = actors; app.jira.store.save(); return roleJson(app, role, actors, project); }
  function versions(request: { params: unknown; query?: unknown }, reply: FastifyReply, paged: boolean) { const project = projectParam(request); if (!project) return fail(reply, 404, "The project does not exist."); let values = projectCoreState(app.jira.store).projects[project.id].versions.map((version) => ({ ...version, project: project.key, projectId: Number(project.id), self: `${app.jira.baseUrl}/rest/api/2/version/${version.id}`, releaseDateSet: Boolean(version.releaseDate), startDateSet: false, overdue: false })); if (!paged) return values; const query = (request.query ?? {}) as Query; const startAt = integer(query.startAt, 0), maxResults = integer(query.maxResults, 50); if (startAt === undefined || maxResults === undefined) return fail(reply, 400, "startAt and maxResults must be non-negative."); if (query.orderBy === "-name") values.reverse(); const selected = values.slice(startAt, startAt + maxResults); return { self: `${app.jira.baseUrl}/rest/api/2/project/${project.id}/version`, startAt, maxResults, total: values.length, isLast: startAt + selected.length >= values.length, values: selected }; }
  function permissionScheme(request: { params: unknown; body?: unknown }, reply: FastifyReply, assign = false) { const project = projectParam(request, "projectKeyOrId"); if (!project) return fail(reply, 404, "The project does not exist."); const details = projectCoreState(app.jira.store).projects[project.id]; const state = getSchemesState(app.jira.store); if (assign) { const body = object(request.body); const target = state.permissionSchemes.find((value) => value.id === body?.id); if (!target) return fail(reply, 404, "The permission scheme does not exist."); details.permissionSchemeId = target.id; app.jira.store.save(); return permissionSchemeJson(app, target); } const scheme = state.permissionSchemes.find((value) => value.id === details.permissionSchemeId); return scheme ? permissionSchemeJson(app, scheme) : fail(reply, 404, "No permission scheme is assigned."); }
  function priorityScheme(request: { params: unknown; body?: unknown }, reply: FastifyReply, assign = false) { const project = projectParam(request, "projectKeyOrId"); if (!project) return fail(reply, 404, "The project does not exist."); const details = projectCoreState(app.jira.store).projects[project.id]; const state = screensPriorityState(app.jira.store); if (assign) { const body = object(request.body); const target = state.prioritySchemes.find((value) => value.id === body?.id); if (!target) return fail(reply, 404, "The priority scheme does not exist."); state.prioritySchemes.forEach((scheme) => scheme.projectKeys = scheme.projectKeys.filter((key) => key !== project.key)); target.projectKeys.push(project.key); details.prioritySchemeId = target.id; app.jira.store.save(); return prioritySchemeJson(app, target); } const scheme = state.prioritySchemes.find((value) => value.id === details.prioritySchemeId); return scheme ? prioritySchemeJson(app, scheme) : fail(reply, 404, "No priority scheme is assigned."); }
  function roleMutation(request: { params: unknown; body: unknown }, reply: FastifyReply, mode: "create" | "full" | "partial") { const state = projectCoreState(app.jira.store); const body = object(request.body); const id = mode === "create" ? undefined : String((request.params as { id: string }).id); const role = id ? state.roles.find((value) => String(value.id) === id) : undefined; if (id && !role) return fail(reply, 404, "The project role does not exist."); const name = body?.name === undefined && role ? role.name : typeof body?.name === "string" ? body.name.trim() : ""; if (!body || !name || (mode === "full" && typeof body.description !== "string")) return fail(reply, 400, "A valid role name and description are required."); if (state.roles.some((value) => value.id !== role?.id && value.name.toLowerCase() === name.toLowerCase())) return fail(reply, mode === "create" ? 409 : 400, "A role with this name already exists."); if (role) Object.assign(role, { name, ...(typeof body.description === "string" ? { description: body.description } : {}) }); else { const created = { id: state.roleCounter++, name, description: typeof body.description === "string" ? body.description : "" }; state.roles.push(created); state.defaultRoleActors[String(created.id)] = { users: [], groups: [] }; app.jira.store.save(); return roleJson(app, created); } app.jira.store.save(); return roleJson(app, role); }
  function globalActors(request: { params: unknown; body?: unknown; query?: unknown }, reply: FastifyReply, mode: "add" | "delete" | undefined = undefined) { const { id } = request.params as { id: string }; const state = projectCoreState(app.jira.store); if (!state.roles.some((role) => String(role.id) === id)) return fail(reply, 404, "The project role does not exist."); let actors = state.defaultRoleActors[id] ?? { users: [], groups: [] }; if (mode === "add") { const body = object(request.body); const incoming = body ? actorSet(body, false) : undefined; if (!incoming) return fail(reply, 400, "Valid user and group arrays are required."); actors = { users: [...new Set([...actors.users, ...incoming.users])], groups: [...new Set([...actors.groups, ...incoming.groups])] }; state.defaultRoleActors[id] = actors; app.jira.store.save(); } else if (mode === "delete") { const query = (request.query ?? {}) as Query; const users = list(query.user), groups = list(query.group); if (!users.length && !groups.length) return fail(reply, 400, "A user or group is required."); actors = { users: actors.users.filter((value) => !users.includes(value)), groups: actors.groups.filter((value) => !groups.includes(value)) }; state.defaultRoleActors[id] = actors; app.jira.store.save(); } return { actors: actorJson(app, actors) }; }
};

function permissionCatalog(havePermission: boolean) { return Object.fromEntries([{ key: "BROWSE_PROJECTS", name: "Browse Projects", type: "PROJECT" }, { key: "CREATE_ISSUES", name: "Create Issues", type: "PROJECT" }, { key: "ADMINISTER", name: "Jira Administrators", type: "GLOBAL" }].map((permission) => [permission.key, { id: permission.key, key: permission.key, name: permission.name, description: permission.name, type: permission.type, havePermission }])); }

export default routes;
