import type {
  JiraIssue,
  JiraNamedResource,
  JiraProject,
  JiraState,
  JiraStatus,
  JiraUser,
} from "./types.js";

const avatarUrls = {
  "16x16": "/secure/useravatar?size=xsmall",
  "24x24": "/secure/useravatar?size=small",
  "32x32": "/secure/useravatar?size=medium",
  "48x48": "/secure/useravatar?size=large",
};

const developer: JiraUser = {
  key: "developer",
  name: "developer",
  emailAddress: "developer@example.test",
  avatarUrls,
  displayName: "Local Developer",
  active: true,
  timeZone: "UTC",
  locale: "en_US",
};

const alex: JiraUser = {
  key: "alex",
  name: "alex",
  emailAddress: "alex@example.test",
  avatarUrls,
  displayName: "Alex Example",
  active: true,
  timeZone: "UTC",
  locale: "en_US",
};

const projects: JiraProject[] = [
  {
    id: "10000",
    key: "T101LIB",
    name: "T101 Common Libraries",
    projectTypeKey: "software",
    simplified: false,
    archived: false,
    lead: developer,
    avatarUrls,
  },
  {
    id: "10001",
    key: "T101OPS",
    name: "T101 Common Delivery Operations",
    projectTypeKey: "software",
    simplified: false,
    archived: false,
    lead: alex,
    avatarUrls,
  },
  {
    id: "10002",
    key: "T100ZB",
    name: "T100 Software Factory",
    projectTypeKey: "software",
    simplified: false,
    archived: false,
    lead: developer,
    avatarUrls,
  },
];

const issueTypes: JiraNamedResource[] = [
  { id: "10001", name: "Story", description: "A user story", subtask: false },
  { id: "10002", name: "Bug", description: "A software defect", subtask: false },
  { id: "10003", name: "Task", description: "A task that needs to be done", subtask: false },
];

const priorities: JiraNamedResource[] = [
  { id: "1", name: "Highest" },
  { id: "2", name: "High" },
  { id: "3", name: "Medium" },
  { id: "4", name: "Low" },
];

const statuses: JiraStatus[] = [
  {
    id: "10000",
    name: "To Do",
    description: "Work has not started",
    statusCategory: { id: 2, key: "new", colorName: "blue-gray", name: "To Do" },
  },
  {
    id: "3",
    name: "In Progress",
    description: "Work is in progress",
    statusCategory: { id: 4, key: "indeterminate", colorName: "yellow", name: "In Progress" },
  },
  {
    id: "10001",
    name: "Done",
    description: "Work is complete",
    statusCategory: { id: 3, key: "done", colorName: "green", name: "Done" },
  },
];

function issue(
  id: string,
  key: string,
  project: JiraProject,
  issueType: JiraNamedResource,
  summary: string,
  description: string,
  status: JiraStatus,
  priority: JiraNamedResource,
  assignee: JiraUser | null,
  created: string,
  labels: string[],
  storyPoints?: number,
): JiraIssue {
  return {
    expand: "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
    id,
    key,
    fields: {
      project,
      issuetype: issueType,
      summary,
      description,
      status,
      priority,
      assignee,
      reporter: developer,
      labels,
      created,
      updated: created,
      comment: { comments: [], maxResults: 0, total: 0, startAt: 0 },
      ...(storyPoints === undefined ? {} : { customfield_10002: storyPoints }),
    },
  };
}

export function createDefaultState(): JiraState {
  const initial: JiraState = {
    issueCounter: 10016,
    commentCounter: 1,
    resources: {},
    users: [developer, alex],
    projects,
    issueTypes,
    priorities,
    statuses,
    issues: [
      issue(
        "10001",
        "T101LIB-1",
        projects[0],
        issueTypes[0],
        "Publish the shared TypeScript logging library",
        "Provide a tenant-neutral logging package that application teams can consume from common repositories.",
        statuses[2],
        priorities[2],
        developer,
        "2026-01-05T09:00:00.000+0000",
        ["common-code", "library", "logging"],
        3,
      ),
      issue(
        "10002",
        "T101LIB-2",
        projects[0],
        issueTypes[1],
        "Shared authentication client fails after token rotation",
        "Consumers of the common authentication client cannot refresh credentials after a signing-key rotation.",
        statuses[0],
        priorities[1],
        alex,
        "2026-01-12T14:30:00.000+0000",
        ["common-code", "authentication", "agent-training"],
        5,
      ),
      issue(
        "10003",
        "T101OPS-1",
        projects[1],
        issueTypes[2],
        "Publish the reusable deployment rollback template",
        "Provide a common rollback job and runbook that every tenant pipeline can import.",
        statuses[1],
        priorities[2],
        developer,
        "2026-01-20T11:15:00.000+0000",
        ["common-code", "pipeline-template", "deployment"],
      ),
      issue(
        "10004",
        "T100ZB-1",
        projects[2],
        issueTypes[0],
        "Publish a golden-path service template",
        "Provide a supported TypeScript service template with CI, tests, health checks, and deployment manifests.",
        statuses[2],
        priorities[1],
        developer,
        "2026-02-02T08:30:00.000+0000",
        ["golden-path", "templates", "developer-experience"],
        8,
      ),
      issue(
        "10005",
        "T100ZB-2",
        projects[2],
        issueTypes[1],
        "Integration test stage fails intermittently",
        "The integration test stage fails around one in five runs without a consistent failing test.",
        statuses[0],
        priorities[0],
        alex,
        "2026-02-04T13:10:00.000+0000",
        ["ci", "flaky-test", "pipeline"],
        5,
      ),
      issue(
        "10006",
        "T100ZB-3",
        projects[2],
        issueTypes[2],
        "Enable dependency vulnerability scanning",
        "Add dependency scanning to the default pipeline and publish findings as build artifacts.",
        statuses[1],
        priorities[1],
        developer,
        "2026-02-06T10:00:00.000+0000",
        ["security", "supply-chain", "pipeline"],
      ),
      issue(
        "10007",
        "T100ZB-4",
        projects[2],
        issueTypes[0],
        "Configure artifact retention policies",
        "Define retention periods for snapshots, release candidates, and production artifacts.",
        statuses[0],
        priorities[2],
        alex,
        "2026-02-08T09:45:00.000+0000",
        ["artifacts", "governance"],
        3,
      ),
      issue(
        "10008",
        "T100ZB-5",
        projects[2],
        issueTypes[0],
        "Create ephemeral environments for merge requests",
        "Provision an isolated environment for each merge request and remove it when the merge request closes.",
        statuses[1],
        priorities[1],
        developer,
        "2026-02-11T15:20:00.000+0000",
        ["environments", "preview", "kubernetes"],
        13,
      ),
      issue(
        "10009",
        "T100ZB-6",
        projects[2],
        issueTypes[2],
        "Generate signed release provenance",
        "Attach signed provenance metadata to every production artifact.",
        statuses[0],
        priorities[1],
        alex,
        "2026-02-14T11:00:00.000+0000",
        ["release", "provenance", "supply-chain"],
      ),
      issue(
        "10010",
        "T100ZB-7",
        projects[2],
        issueTypes[2],
        "Document the service onboarding path",
        "Explain how teams create, register, deploy, and operate a service through the software factory.",
        statuses[2],
        priorities[3],
        developer,
        "2026-02-17T08:15:00.000+0000",
        ["documentation", "onboarding", "golden-path"],
      ),
      issue(
        "10011",
        "T100ZB-8",
        projects[2],
        issueTypes[1],
        "Monorepo pipeline exceeds twenty minutes",
        "Unchanged packages are rebuilt and retested on every merge request.",
        statuses[0],
        priorities[1],
        alex,
        "2026-02-19T16:40:00.000+0000",
        ["performance", "ci", "monorepo"],
        8,
      ),
      issue(
        "10012",
        "T100ZB-9",
        projects[2],
        issueTypes[2],
        "Automate build-secret rotation",
        "Rotate registry and signing credentials without interrupting active pipelines.",
        statuses[1],
        priorities[0],
        developer,
        "2026-02-21T12:30:00.000+0000",
        ["security", "secrets", "automation"],
      ),
      issue(
        "10013",
        "T100ZB-10",
        projects[2],
        issueTypes[0],
        "Add deployment-frequency and lead-time dashboard",
        "Calculate DORA delivery metrics from pipeline and deployment events.",
        statuses[0],
        priorities[2],
        alex,
        "2026-02-24T09:10:00.000+0000",
        ["observability", "dora", "metrics"],
        8,
      ),
      issue(
        "10014",
        "T100ZB-11",
        projects[2],
        issueTypes[0],
        "Autoscale shared build runners",
        "Scale runner capacity from queue depth while maintaining workload isolation.",
        statuses[2],
        priorities[1],
        developer,
        "2026-02-26T14:00:00.000+0000",
        ["runners", "autoscaling", "infrastructure"],
        13,
      ),
      issue(
        "10015",
        "T100ZB-12",
        projects[2],
        issueTypes[2],
        "Generate an SBOM for every release",
        "Produce CycloneDX software bills of materials and retain them with release artifacts.",
        statuses[0],
        priorities[1],
        alex,
        "2026-02-28T10:25:00.000+0000",
        ["sbom", "security", "release"],
      ),
    ],
  };

  return structuredClone(initial);
}
